name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ---------------------------
      # SSH into EC2
      # ---------------------------
      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          # Login to ECR
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}

          # Pull new images
          docker pull ${{ secrets.ECR_URI }}/bookstore-backend:latest
          docker pull ${{ secrets.ECR_URI }}/bookstore-frontend:latest

          # Stop old containers (ignore errors)
          docker stop backend-container || true
          docker stop frontend-container || true

          # Remove old containers
          docker rm backend-container || true
          docker rm frontend-container || true

          # Run backend
          docker run -d --name backend-container -p 8080:8080 \
            ${{ secrets.ECR_URI }}/bookstore-backend:latest

          # Run frontend
          docker run -d --name frontend-container -p 80:80 \
            ${{ secrets.ECR_URI }}/bookstore-frontend:latest

          EOF
