name: Deploy Monitoring

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#      - monitoring

env:
  AWS_REGION: us-east-2
  TF_DIR: terraform-code-eks

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.0

      # Update kubeconfig for EKS
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name bookstore-eks

      # Terraform Init
      - name: Terraform Init
        run: terraform -chdir=${TF_DIR} init

      # Terraform Plan
      - name: Terraform Plan (Monitoring Only)
        run: terraform -chdir=${TF_DIR} plan \
          -target=kubernetes_config_map.prometheus_config \
          -target=kubernetes_config_map.alertmanager_config \
          -target=kubernetes_deployment_v1.prometheus \
          -target=kubernetes_service_v1.prometheus \
          -target=kubernetes_deployment_v1.alertmanager \
          -target=kubernetes_service_v1.alertmanager

      # Terraform Apply
      - name: Terraform Apply (Monitoring Only)
        run: terraform -chdir=${TF_DIR} apply -auto-approve \
          -target=kubernetes_config_map.prometheus_config \
          -target=kubernetes_config_map.alertmanager_config \
          -target=kubernetes_deployment_v1.prometheus \
          -target=kubernetes_service_v1.prometheus \
          -target=kubernetes_deployment_v1.alertmanager \
          -target=kubernetes_service_v1.alertmanager
